routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

// //route to test email. Enter the user id.
//Route::get('/mail', function() {
//    $user = \App\User::find(10);
//    return new \App\Mail\UserApprovedEmail($user);
//});

Auth::routes();

Route::get('/', 'PagesController@home');
Route::get('/policy-agreement', 'PagesController@policyAgreement')->name('policyAgreement');
Route::get('/agree-to-policy-agreement', 'PagesController@agreeToPolicyAgreement')->name('agreeToPolicyAgreement');
Route::get('/privacy', 'PagesController@privacy')->name('privacy');
Route::get('/terms', 'PagesController@terms')->name('terms');
Route::get('/guidelines', 'PagesController@guidelines')->name('guidelines');
Route::get('/search/{query?}/{page?}', 'SearchController@searchPage')->name('searchPage');
Route::get('/search_posts/{query}', 'SearchController@searchPosts');
Route::get('/menu_search/{query}', 'SearchController@menuSearch');

Route::get('/verification-email-sent', 'VerificationController@verificationEmailSent')->name('verify.verificationEmailSent');
Route::get('/verification-email-resent', 'VerificationController@verificationEmailResent')->name('verify.verificationEmailResent');
Route::get('/verify-email/{verification_token}', 'VerificationController@verifyEmail')->name('verify.verifyEmail');
Route::get('/email-verified', 'VerificationController@emailVerified')->name('verify.emailVerified');
Route::get('/email-not-verified/{auth_token}', 'VerificationController@emailNotVerified')->name('verify.emailNotVerified');
Route::get('/resend-verification-email/{auth_token}', 'VerificationController@resendVerificationEmail')->name('verify.resendVerificationEmail');
Route::get('/banned-user', 'VerificationController@bannedUser')->name('verify.bannedUser');

Route::get('/dashboard', 'DashboardController@summary')->name('dashboard');
Route::get('/dashboard/posts', 'DashboardController@posts')->name('dashboard.posts');
Route::get('/dashboard/views', 'DashboardController@views')->name('dashboard.views');
Route::get('/dashboard/profile', 'DashboardController@profile')->name('dashboard.profile');
Route::get('/dashboard/payments', 'DashboardController@payments')->name('dashboard.payments');
Route::get('/dashboard/users-management', 'DashboardController@usersManagement')->name('dashboard.usersManagement');
Route::get('/dashboard/posts-management', 'DashboardController@postsManagement')->name('dashboard.postsManagement');
Route::get('/dashboard/categories', 'DashboardController@categories')->name('dashboard.categories');
Route::post('/dashboard/categories', 'DashboardController@storeCategories')->name('dashboard.storeCategories');
Route::get('/dashboard/settings', 'DashboardController@settings')->name('dashboard.settings');

Route::put('/dashboard/update-profile', 'DashboardController@updateProfile');
Route::put('/dashboard/save-profile-image', 'DashboardController@saveProfileImage');
Route::put('/dashboard/update-personal-info', 'DashboardController@updatePersonalInfo');
Route::put('/dashboard/update-password', 'DashboardController@updatePassword');
Route::get('/dashboard/delete-my-account', 'UsersController@deleteMyAccount')->name('users.deleteMyAccount');
Route::get('/dashboard/search_posts', 'DashboardController@searchPosts');
Route::get('/dashboard/search_posts_for_all_users', 'DashboardController@searchPostsForAllUsers');
Route::get('/dashboard/search_users', 'DashboardController@searchUsers');
Route::get('/dashboard/search_views', 'DashboardController@searchViews');

Route::get('/users/{user}/manage', 'UsersController@manage')->name('users.manage');
Route::get('/users/{user}/approve', 'UsersController@approve')->name('users.approve');
Route::put('/users/{user}/reject', 'UsersController@reject')->name('users.reject');
Route::get('/users/{user}/suspend', 'UsersController@suspend')->name('users.suspend');
Route::get('/users/{user}/unsuspend', 'UsersController@unsuspend')->name('users.unsuspend');
Route::get('/users/{user}/ban', 'UsersController@ban')->name('users.ban');
Route::get('/users/{user}/unban', 'UsersController@unban')->name('users.unban');
Route::put('/users/self-deactivate', 'UsersController@selfDeactivate')->name('users.selfDeactivate');
Route::put('/users/self-reactivate', 'UsersController@selfReactivate')->name('users.selfReactivate');
Route::put('/users/self-delete', 'UsersController@selfDelete')->name('users.selfDelete');
Route::get('/users/account-deleted', 'UsersController@accountDeleted')->name('users.accountDeleted');
Route::get('/users/{user}', 'UsersController@show')->name('users.show');


Route::get('/posts/{draft}/edit', 'DraftsController@edit')->name('drafts.edit');
Route::put('/drafts/{draft}/update-category', 'DraftsController@updateCategory');
Route::put('/drafts/{draft}/update-media-type', 'DraftsController@updateMediaType');
Route::put('/drafts/{draft}/update-title', 'DraftsController@updateTitle');
Route::put('/drafts/{draft}/update-text', 'DraftsController@updateText');
Route::put('/drafts/{draft}/upload-image', 'DraftsController@uploadImage');
Route::put('/drafts/{draft}/reorder-images', 'DraftsController@reorderImages');
Route::delete('/drafts/{draft}/delete-image', 'DraftsController@deleteImage');
Route::put('/drafts/{draft}/update-video-id', 'DraftsController@updateVideoId');
Route::put('/drafts/{draft}/publish', 'DraftsController@publish');
Route::put('/drafts/{draft}/cancel-changes', 'DraftsController@cancelChanges');
Route::put('/drafts/{draft}/delete', 'DraftsController@delete');

Route::get('/posts/create', 'DraftsController@create')->name('drafts.create');
Route::put('/posts/toggle-remove', 'PostsController@toggleRemove')->name('posts.toggleRemove');

Route::get('/{category}/{post_slug}/{post_id}', 'PostsController@show')->name('posts.show');
// *** important *** this route should be last for performance reasons
Route::get('/{category}', 'PagesController@category')->name('category');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Builder;

class Post extends Model
{
    // for scout/algolia
    use Searchable;
    use SoftDeletes;

    protected $fillable = [
        'title', 'text', 'slug', 'category_id', 'user_id', 'media_type', 'image'
    ];

    protected $casts = [
        'self_deactivated' => 'boolean',
    ];

    // for soft delete
    protected $dates = ['deleted_at'];

    /******** Relationships ********/
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function postImages()
    {
        return $this->hasMany('App\PostImage')->orderBy('order', 'asc');
    }

    public function postVideos()
    {
        return $this->hasMany('App\PostVideo');
    }

    public function toSearchableArray()
    {
        /**
         * Load the categories relation so that it's available by algolia
         *  in the laravel toArray method
         */
        $this->user;
        $this->category;

        return $this->toArray();
    }

    /******** Scopes ********/
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('active', function (Builder $builder) {
            $builder->where('self_deactivated', 0);
        });
    }

    /******** Accessors & Mutators ********/
    public function getPublicationDateAttribute()
    {
        $publicationDate = $this->created_at->diffInDays(\Carbon\Carbon::now()) >= 7 ? $this->created_at->format('M j, Y') : $this->created_at->diffForHumans();
        return $publicationDate;
    }

    public function getExcerptTitleAttribute()
    {
        $excerptTitle = str_limit(strip_tags($this->title), 40, '...');
        return $excerptTitle;
    }

    public function getExcerptTextAttribute()
    {
        $text = str_replace('><', '> <', $this->text);
        $excerptText = str_limit(strip_tags($text), 150, '...');
        return $excerptText;
    }

    // This method should be cached when used
    public function getAllImagesAttribute()
    {
        try {
            $largeImage = [];
            foreach ($this->postImages as $image) {
                if (Storage::disk('s3')->exists("posts/large/".$image->filename)) {
                    $largeImage[] = Storage::disk('s3')->url("posts/large/".$image->filename);
                } else {
                    $largeImage[] = '/images/image_not_available.png';
                }
            }
        } catch (\Exception $e) {
            $largeImage = '/images/image_not_available.png';
        }
        return $largeImage;
    }

    // This method should be cached when used
    public function getExcerptImage($size = 'large')
    {
        try {
            if ($this->media_type == "youtube" || $this->media_type == "vimeo") {
                $excerptImage = getMediaImageUrl($this->media_type, $this->postVideos->where('type', $this->media_type)->first()->video_id);
            } elseif(Storage::disk('s3')->exists("posts/$size/".$this->postImages->where('order', 0)->first()->filename)) {
                $excerptImage = Storage::disk('s3')->url("posts/$size/".$this->postImages->where('order', 0)->first()->filename);
            } else {
                $excerptImage = '/images/image_not_available.png';
            }
        } catch (\Exception $e) {
            $excerptImage = '/images/image_not_available.png';
        }
        return $excerptImage;
    }

    // This method should be cached when used
    public function getLargeImageAttribute()
    {
        return $this->getExcerptImage();
    }

    // This method should be cached when used
    public function getMediumImageAttribute()
    {
        return $this->getExcerptImage('medium');
    }

    // This method should be cached when used
    public function getSmallImageAttribute()
    {
        return $this->getExcerptImage('small');
    }

    /******** Methods with Redis caching ********/
    public static function getCachedPost($postId)
    {
        return Cache::tags(["post_$postId"])->remember("post_$postId", config('app.redis_caching_time'), function () use ($postId) {
            $post = Post::where('id', $postId)->with('user', 'category', 'postImages', 'postVideos')->first();
            $post->excerpt_text = $post->excerpt_text;
            $post->excerpt_title = $post->excerpt_title;
            if($post->media_type == 'image') {
                $post->all_images = $post->all_images;
                $post->large_image = $post->large_image;
                $post->medium_image = $post->medium_image;
                $post->small_image = $post->small_image;
            }
            if($post->media_type == 'youtube' or $post->media_type == 'vimeo') {
                $post->video_url = getVideoUrl($post->media_type, $post->postVideos()->where('type', $post->media_type)->first()->video_id, false);
            }
            return $post;
        });
    }

    public static function getDateOfThirtiethPost()
    {
        return Cache::tags(['posts'])->remember('date_of_thirtieth_post', config('app.redis_caching_time_medium'), function () {
            return Post::select('created_at')->orderBy('created_at', 'desc')->take(30)->get()->last()->created_at;
        });
    }

    // get the 6 most trending posts among all categories together. Calculated from the date of the 30th post.
    public static function trending()
    {
        return Cache::tags(['posts'])->remember('trending_posts', config('app.redis_caching_time_medium'), function () {
            $postsIds = Post::leftJoin('views', 'posts.id', '=', 'views.post_id')
                ->select('posts.id', DB::raw('IFNULL(SUM(views.total), 0) as total_views'))
                ->where('posts.created_at', '>=', Post::getDateOfThirtiethPost())
                ->groupBy('posts.id')
                ->orderBy('total_views', 'desc')
                ->orderBy('posts.created_at', 'desc')
                ->take(6)->pluck('id');
            foreach($postsIds as $postId) {
                $posts[] = Post::getCachedPost($postId);
            }
            return $posts;
        });
    }

    public static function trendingForCategory($categoryId)
    {
        return Cache::tags(['posts'])->remember("trending_posts_for_category_$categoryId", config('app.redis_caching_time_medium'), function () use ($categoryId) {
            $daysBack = Post::select('created_at')->where('category_id', '=', $categoryId)->orderBy('created_at', 'desc')->take(30)->get()->last()->created_at;
            $postsIds = Post::leftJoin('views', 'posts.id', '=', 'views.post_id')
                ->select('posts.id', DB::raw('IFNULL(SUM(views.total), 0) as total_views'))
                ->where('posts.category_id', '=', $categoryId)
                ->where('posts.created_at', '>=', $daysBack)
                ->groupBy('posts.id')
                ->orderBy('total_views', 'desc')
                ->orderBy('posts.created_at', 'desc')
                ->take(6)->pluck('id');
            foreach($postsIds as $postId) {
                $posts[] = Post::getCachedPost($postId);
            }
            return $posts;
        });
    }

    public static function trendingForAllCategories()
    {
        return Cache::tags(['posts'])->remember('trending_posts_for_all_categories', config('app.redis_caching_time_medium'), function () {
            foreach (Category::orderedByTrending() as $trendingCategory) {
                $trendingPostsForAllCategories[] = Post::trendingForCategory($trendingCategory->id);
            }
            return $trendingPostsForAllCategories;
        });
    }

    public static function latests()
    {
        return Cache::tags(['posts'])->remember('latest_posts', config('app.redis_caching_time_medium'), function () {
            $postsIds = Post::orderBy('created_at', 'desc')->take(3)->pluck('id');
            foreach($postsIds as $postId) {
                $posts[] = Post::getCachedPost($postId);
            }
            return $posts;
        });
    }

    public static function latestsForCategory($categoryId)
    {
        return Cache::tags(['posts'])->remember("latests_posts_for_category_$categoryId", config('app.redis_caching_time_medium'), function () use ($categoryId) {
            $postsIds = Post::where('category_id', '=', $categoryId)->orderBy('created_at', 'desc')->take(18)->pluck('id');
            foreach($postsIds as $postId) {
                $posts[] = Post::getCachedPost($postId);
            }
            return $posts;
        });
    }

    public static function suggestions()
    {
        return Cache::tags(['posts'])->remember('suggestions_posts', config('app.redis_caching_time_medium'), function () {
            $postsIds = Post::where('created_at', '>=', Carbon::today()->subDays(100))->inRandomOrder()->take(3)->pluck('id');
            foreach($postsIds as $postId) {
                $posts[] = Post::getCachedPost($postId);
            }
            return $posts;
        });
    }

    public static function byThisAuthor($userId)
    {
        return Cache::tags(['posts'])->remember("by_this_author_$userId", config('app.redis_caching_time_medium'), function () use ($userId) {
            $postsIds = Post::where('user_id', '=', $userId)->inRandomOrder()->take(3)->pluck('id');
            foreach($postsIds as $postId) {
                $posts[] = Post::getCachedPost($postId);
            }
            return $posts;
        });
    }

    public static function totalViewsForPost($postId)
    {
        return Cache::tags(["post_$postId"])->remember("total_views_for_post_$postId", config('app.redis_caching_time_short'), function () use ($postId) {

resources/views/_most_popular.blade.php
<section id="most-popular">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <img class="padding-bottom img-responsive hidden-md hidden-lg" src="/images/adv-banner.jpg" alt="">
            </div>
            <div class="col-xs-12 col-md-6 first-position">
                <div class="img-container" data-aspect-ratio="big-custom">
                    <a href="{{ route('posts.show', ['category' => $trendingPosts->first()->category->url, 'post_slug' => $trendingPosts->first()->slug, 'post' => $trendingPosts->first()->id]) }}">
                        <span class="color-overlay"></span>
                        <div class="text-overlay">
                            <div class="bottom-left">
                                <button class="x-small">{{ $trendingPosts->first()->category->name }}</button>
                                <h2>{{ $trendingPosts->first()->excerptTitle }}</h2>
                                <p class="info">
                                    <span class="author">{{ $trendingPosts->first()->user->public_name }}</span>
                                    <span class="date">&middot; {{ $trendingPosts->first()->publication_date }}</span>
                                </p>
                            </div>
                        </div>
                        <lazyload-img :imgsrc="'{{ $trendingPosts->first()->largeImage }}'" :uniquename="'{{ "post_" . $trendingPosts->first()->id }}'" :title="'{{ $trendingPosts->first()->title }}'"></lazyload-img>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="row">
                    @foreach($trendingPosts->slice(1, 4) as $post)
                        <div class="col-xs-6">
                            <div class="img-container" data-aspect-ratio="custom">
                                <a href="{{ route('posts.show', ['category' => $post->category->url, 'post_slug' => $post->slug, 'post' => $post->id]) }}">
                                    <span class="color-overlay"></span>
                                    <div class="text-overlay">
                                        <div class="bottom-left">
                                            <button class="x-small">{{ $post->category->name }}</button>
                                            <h3>{{ $post->excerptTitle }}</h3>
                                        </div>
                                    </div>
                                    <lazyload-img :imgsrc="'{{ $post->mediumImage }}'" :uniquename="'{{ "post_" . $post->id }}'"></lazyload-img>
                                </a>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/_post_excerpt.blade.php
<div data-aspect-ratio="custom" class="img-container">
<a href="{{ route('posts.show', ['category_url' => $post->category->url, 'post_slug' => $post->slug, 'post' => $post->id]) }}">
<lazyload-img :imgsrc="'{{ $post->mediumImage }}'" :uniquename="'{{ "post_" . $post->id }}'" :title="'{{ $post->title }}'"></lazyload-img>
</a>
</div>
<h4><a href="{{ route('posts.show', ['category_url' => $post->category->url, 'post_slug' => $post->slug, 'post' => $post->id]) }}">{{ $post->excerptTitle }}</a></h4>
<p class="info">
<span><a class="author" href="{{ route('users.show', ['user' => $post->user->url]) }}">{{ $post->user->real_name }}</a></span>
<span class="date">&middot; {{ $post->publication_date }}</span>
</p>
<p><a class="excerpt" href="{{ route('posts.show', ['category_url' => $post->category->url, 'post_slug' => $post->slug, 'post' => $post->id]) }}">{{ $post->excerptText }}</a></p>

resources/views/_privacy.blade.php
<div id="privacy" class="padding-vt">
    <h2>Privacy Policy</h2>
    <p>Your privacy is important to us. It is News' policy to respect your privacy regarding any information we may collect from you across our website, <a href="http://news.test">http://news.test</a>, and other sites we own and operate.</p>
    <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
    <p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification.</p>
    <p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
    <p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
    <p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
    <p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
    <p>This policy is effective as of 27 May 2018.</p>
</div>

resources/views/_sidebar.blade.php
<div class="sidebar show-lg">
    <adsense
            ad-client="ca-pub-3937376096447808"
            ad-slot="3112785579"
            ad-style="display: block"
            ad-format="auto">
    </adsense>
    <adsense
            ad-client="ca-pub-3937376096447808"
            ad-slot="3112785579"
            ad-style="display: block"
            ad-format="auto">
    </adsense>
    <adsense
            ad-client="ca-pub-3937376096447808"
            ad-slot="3112785579"
            ad-style="display: block"
            ad-format="auto">
    </adsense>
    <adsense
            ad-client="ca-pub-3937376096447808"
            ad-slot="3112785579"
            ad-style="display: block"
            ad-format="auto">
    </adsense>
    {{--<div class="adv-img-container">--}}
        {{--<img src="/images/advertisement.jpg" alt="">--}}
    {{--</div>--}}
    {{--<div class="adv-img-container">--}}
        {{--<img src="/images/advertisement.jpg" alt="">--}}
    {{--</div>--}}
    {{--<div class="adv-img-container">--}}
        {{--<img src="/images/advertisement.jpg" alt="">--}}
    {{--</div>--}}
    {{--<div class="adv-img-container">--}}
        {{--<img src="/images/advertisement.jpg" alt="">--}}
    {{--</div>--}}
    {{--<div class="adv-img-container">--}}
        {{--<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>--}}
        {{--<!-- new responsive -->--}}
        {{--<ins class="adsbygoogle"--}}
             {{--style="display:block"--}}
             {{--data-ad-client="ca-pub-3937376096447808"--}}
             {{--data-ad-slot="3112785579"--}}
             {{--data-ad-format="auto"></ins>--}}
        {{--<script>--}}
            {{--(adsbygoogle = window.adsbygoogle || []).push({});--}}
        {{--</script>--}}
    {{--</div>--}}
</div>

resources/views/_terms.blade.php
<div id="terms" class="padding-vt">
    <h2>News Terms of Service</h2>
    <h3>1. Terms</h3>
    <p>By accessing the website at <a href="http://news.test">http://news.test</a>, you are agreeing to be bound by
        these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance
        with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or
        accessing this site. The materials contained in this website are protected by applicable copyright and trademark
        law.</p>
    <h3>2. Use License</h3>
    <ol type="a">
        <li>Permission is granted to temporarily download one copy of the materials (information or software) on News'
            website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer
            of title, and under this license you may not:
            <ol type="i">
                <li>modify or copy the materials;</li>
                <li>use the materials for any commercial purpose, or for any public display (commercial or
                    non-commercial);
                </li>
                <li>attempt to decompile or reverse engineer any software contained on News' website;</li>
                <li>remove any copyright or other proprietary notations from the materials; or</li>
                <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
            </ol>
        </li>
        <li>This license shall automatically terminate if you violate any of these restrictions and may be terminated by
            News at any time. Upon terminating your viewing of these materials or upon the termination of this license,
            you must destroy any downloaded materials in your possession whether in electronic or printed format.
        </li>
    </ol>
    <h3>3. Disclaimer</h3>
    <ol type="a">
        <li>The materials on News' website are provided on an 'as is' basis. News makes no warranties, expressed or
            implied, and hereby disclaims and negates all other warranties including, without limitation, implied
            warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of
            intellectual property or other violation of rights.
        </li>
        <li>Further, News does not warrant or make any representations concerning the accuracy, likely results, or
            reliability of the use of the materials on its website or otherwise relating to such materials or on any
            sites linked to this site.
        </li>
    </ol>
    <h3>4. Limitations</h3>
    <p>In no event shall News or its suppliers be liable for any damages (including, without limitation, damages for
        loss of data or profit, or due to business interruption) arising out of the use or inability to use the
        materials on News' website, even if News or a News authorized representative has been notified orally or in
        writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied
        warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply
        to you.</p>
    <h3>5. Accuracy of materials</h3>
    <p>The materials appearing on News' website could include technical, typographical, or photographic errors. News
        does not warrant that any of the materials on its website are accurate, complete or current. News may make
        changes to the materials contained on its website at any time without notice. However News does not make any
        commitment to update the materials.</p>
    <h3>6. Links</h3>
    <p>News has not reviewed all of the sites linked to its website and is not responsible for the contents of any such
        linked site. The inclusion of any link does not imply endorsement by News of the site. Use of any such linked
        website is at the user's own risk.</p>
    <h3>7. Modifications</h3>
    <p>News may revise these terms of service for its website at any time without notice. By using this website you are
        agreeing to be bound by the then current version of these terms of service.</p>
    <h3>8. Governing Law</h3>
    <p>These terms and conditions are governed by and construed in accordance with the laws of Canada and you
        irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
</div>

resources/views/category.blade.php
@extends('layouts.app')
@section('title', 'Home')
@section('bodyId', 'home')
@section('content')
    @include('cached._most_popular', ['trendingPosts' => $trendingPosts])
    @component('templates.main_with_sidebar')
         {{--***** <div class="col-xs-12 col-lg-8 main-content"> ***** --}}
        <div class="category">
            <div class="header">
                <p class="header-title">Latest</p>
            </div>
            <div class="row">
                @foreach($latestPostsForCategory as $post)
                    <div class="col-xs-12 col-sm-6 col-lg-4 padding-bottom-md">
                        @include('cached._post_excerpt', ['post' => $post])
                    </div>
                    @if($loop->iteration % 4 == 0)
                        <div class="col-xs-12 col-sm-6 col-lg-4 padding-bottom-md ad-like hidden-lg">
                            <adsense
                                    ad-client="ca-pub-3937376096447808"
                                    ad-slot="3112785579"
                                    ad-style="display: block"
                                    ad-format="auto">
                            </adsense>
                        </div>
                    @endif
                @endforeach
            </div>
            <div class="row padding-bottom">
                <div class="col-xs-12 col-md-6 hidden-lg">
                    <adsense
                            ad-client="ca-pub-3937376096447808"
                            ad-slot="3112785579"
                            ad-style="display: block"
                            ad-format="auto">
                    </adsense>
                </div>
                <div class="col-xs-12 col-md-6 hidden-lg">
                    <adsense
                            ad-client="ca-pub-3937376096447808"
                            ad-slot="3112785579"
                            ad-style="display: block"
                            ad-format="auto">
                    </adsense>
                </div>
            </div>
        </div>
         {{--***** </div> ***** --}}
    @endcomponent
@endsection

resources/views/guidelines.blade.php
@extends('layouts.app')
@section('title', 'Contact')
@section('bodyId', 'contact')
@section('content')
    @component('templates.main_without_sidebar')
            {{--***** <div class="col-xs-12 main-content"> ***** --}}
                <div class="row padding-top-for-mobile">
                    <div class="col-xs-12 col-md-offset-1 col-sm-10">
                        <h2>Guidelines</h2>
                        <ul class="indented">
                            <li><p>Copyright</p></li>
                            <li><p>Proper english</p></li>
                        </ul>
                    </div>
                </div>
            {{--***** </div> ***** --}}
    @endcomponent
@endsection

resources/views/privacy.blade.php
@extends('layouts.app')
@section('title', 'Contact')
@section('bodyId', 'contact')
@section('content')
    @component('templates.main_without_sidebar')
            {{--***** <div class="col-xs-12 main-content"> ***** --}}
            <div class="row">
                <div class="col-xs-12 col-md-offset-1 col-sm-10">
                    @include('_privacy')
                </div>
            </div>
            {{--***** </div> ***** --}}
    @endcomponent
@endsection