routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

// //route to test email. Enter the user id.
//Route::get('/mail', function() {
//    $user = \App\User::find(10);
//    return new \App\Mail\UserApprovedEmail($user);
//});

Auth::routes();

Route::get('/', 'PagesController@home');
Route::get('/policy-agreement', 'PagesController@policyAgreement')->name('policyAgreement');
Route::get('/agree-to-policy-agreement', 'PagesController@agreeToPolicyAgreement')->name('agreeToPolicyAgreement');
Route::get('/privacy', 'PagesController@privacy')->name('privacy');
Route::get('/terms', 'PagesController@terms')->name('terms');
Route::get('/guidelines', 'PagesController@guidelines')->name('guidelines');
Route::get('/search/{query?}/{page?}', 'SearchController@searchPage')->name('searchPage');
Route::get('/search_posts/{query}', 'SearchController@searchPosts');
Route::get('/menu_search/{query}', 'SearchController@menuSearch');

Route::get('/verification-email-sent', 'VerificationController@verificationEmailSent')->name('verify.verificationEmailSent');
Route::get('/verification-email-resent', 'VerificationController@verificationEmailResent')->name('verify.verificationEmailResent');
Route::get('/verify-email/{verification_token}', 'VerificationController@verifyEmail')->name('verify.verifyEmail');
Route::get('/email-verified', 'VerificationController@emailVerified')->name('verify.emailVerified');
Route::get('/email-not-verified/{auth_token}', 'VerificationController@emailNotVerified')->name('verify.emailNotVerified');
Route::get('/resend-verification-email/{auth_token}', 'VerificationController@resendVerificationEmail')->name('verify.resendVerificationEmail');
Route::get('/banned-user', 'VerificationController@bannedUser')->name('verify.bannedUser');

Route::get('/dashboard', 'DashboardController@summary')->name('dashboard');
Route::get('/dashboard/posts', 'DashboardController@posts')->name('dashboard.posts');
Route::get('/dashboard/views', 'DashboardController@views')->name('dashboard.views');
Route::get('/dashboard/profile', 'DashboardController@profile')->name('dashboard.profile');
Route::get('/dashboard/payments', 'DashboardController@payments')->name('dashboard.payments');
Route::get('/dashboard/users-management', 'DashboardController@usersManagement')->name('dashboard.usersManagement');
Route::get('/dashboard/posts-management', 'DashboardController@postsManagement')->name('dashboard.postsManagement');
Route::get('/dashboard/categories', 'DashboardController@categories')->name('dashboard.categories');
Route::post('/dashboard/categories', 'DashboardController@storeCategories')->name('dashboard.storeCategories');
Route::get('/dashboard/settings', 'DashboardController@settings')->name('dashboard.settings');

Route::put('/dashboard/update-profile', 'DashboardController@updateProfile');
Route::put('/dashboard/save-profile-image', 'DashboardController@saveProfileImage');
Route::put('/dashboard/update-personal-info', 'DashboardController@updatePersonalInfo');
Route::put('/dashboard/update-password', 'DashboardController@updatePassword');
Route::get('/dashboard/delete-my-account', 'UsersController@deleteMyAccount')->name('users.deleteMyAccount');
Route::get('/dashboard/search_posts', 'DashboardController@searchPosts');
Route::get('/dashboard/search_posts_for_all_users', 'DashboardController@searchPostsForAllUsers');
Route::get('/dashboard/search_users', 'DashboardController@searchUsers');
Route::get('/dashboard/search_views', 'DashboardController@searchViews');

Route::get('/users/{user}/manage', 'UsersController@manage')->name('users.manage');
Route::get('/users/{user}/approve', 'UsersController@approve')->name('users.approve');
Route::put('/users/{user}/reject', 'UsersController@reject')->name('users.reject');
Route::get('/users/{user}/suspend', 'UsersController@suspend')->name('users.suspend');
Route::get('/users/{user}/unsuspend', 'UsersController@unsuspend')->name('users.unsuspend');
Route::get('/users/{user}/ban', 'UsersController@ban')->name('users.ban');
Route::get('/users/{user}/unban', 'UsersController@unban')->name('users.unban');
Route::put('/users/self-deactivate', 'UsersController@selfDeactivate')->name('users.selfDeactivate');
Route::put('/users/self-reactivate', 'UsersController@selfReactivate')->name('users.selfReactivate');
Route::put('/users/self-delete', 'UsersController@selfDelete')->name('users.selfDelete');
Route::get('/users/account-deleted', 'UsersController@accountDeleted')->name('users.accountDeleted');
Route::get('/users/{user}', 'UsersController@show')->name('users.show');


Route::get('/posts/{draft}/edit', 'DraftsController@edit')->name('drafts.edit');
Route::put('/drafts/{draft}/update-category', 'DraftsController@updateCategory');
Route::put('/drafts/{draft}/update-media-type', 'DraftsController@updateMediaType');
Route::put('/drafts/{draft}/update-title', 'DraftsController@updateTitle');
Route::put('/drafts/{draft}/update-text', 'DraftsController@updateText');
Route::put('/drafts/{draft}/upload-image', 'DraftsController@uploadImage');
Route::put('/drafts/{draft}/reorder-images', 'DraftsController@reorderImages');
Route::delete('/drafts/{draft}/delete-image', 'DraftsController@deleteImage');
Route::put('/drafts/{draft}/update-video-id', 'DraftsController@updateVideoId');
Route::put('/drafts/{draft}/publish', 'DraftsController@publish');
Route::put('/drafts/{draft}/cancel-changes', 'DraftsController@cancelChanges');
Route::put('/drafts/{draft}/delete', 'DraftsController@delete');

Route::get('/posts/create', 'DraftsController@create')->name('drafts.create');
Route::put('/posts/toggle-remove', 'PostsController@toggleRemove')->name('posts.toggleRemove');

Route::get('/{category}/{post_slug}/{post_id}', 'PostsController@show')->name('posts.show');
// *** important *** this route should be last for performance reasons
Route::get('/{category}', 'PagesController@category')->name('category');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'auth_token', 'verification_token', 'verification_token_created_at', 'application_text',
        'image', 'public_name', 'url', 'title', 'description', 'public_email', 'public_email_2', 'website', 'website_2', 'website_3',
        'facebook', 'twitter', 'google_plus', 'youtube', 'vimeo', 'instagram', 'real_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'auth_token', 'verification_token', 'verification_token_created_at', 'application_text'
    ];

    public function getRouteKeyName()
    {
        return 'url';
    }

    /******** Relationships ********/
    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function drafts()
    {
        return $this->hasMany('App\Draft');
    }

    /******** Roles ********/
    // available roles: Unverified, Applicant, Author, Admin, Superadmin

    public function getIsSuperadminAttribute()
    {
        return $this->role === 'Superadmin';
    }

    public function getIsAdminAttribute()
    {
        return $this->role === 'Admin';
    }

    public function getIsAuthorAttribute()
    {
        return $this->role === 'Author';
    }

    public function getIsApplicantAttribute()
    {
        return $this->role === 'Applicant';
    }

    public function hasRoleOrHigher($role)
    {
        $response = false;
        if($role === 'Applicant') {
            if ($this->role == 'Applicant' || $this->role == 'Author' || $this->role == 'Admin' || $this->role == 'Superadmin') {
                $response = true;
            }
        } elseif($role === 'Author') {
            if($this->role == 'Author' || $this->role == 'Admin' || $this->role == 'Superadmin') {
                $response = true;
            }
        } elseif($role === 'Admin') {
            if($this->role == 'Admin' || $this->role == 'Superadmin') {
                $response = true;
            }
        } elseif($role === 'Superadmin') {
            if ($this->role == 'Superadmin') {
                $response = true;
            }
        }
        return $response;
    }

    /******** Status ********/
    // available status: Rejected, Active, Suspended, Banned

    public function getIsBannedAttribute()
    {
        return $this->status === 'Banned';
    }

    public function getIsBannedOrSelfDeactivatedAttribute()
    {
        return $this->status === 'Banned' || $this->self_deactivated_at != NULL;
    }

    public function getIsSelfDeactivatedAttribute()
    {
        return $this->self_deactivated_at != NULL;
    }

    public function getIsSuspendedAttribute()
    {
        return $this->status === 'Suspended';
    }

    /******** Scopes ********/


    /******** Accessors & Mutators ********/
    public function getDescriptionExcerptAttribute()
    {
        $descriptionExcerpt = str_limit(strip_tags($this->description), 100);
        return $descriptionExcerpt;
    }

    public function getImageAttribute($value)
    {
        try {
            if ($value == NULL or !Storage::disk('s3')->exists($value)) {
                $value = '/images/avatar.jpg';
            }
        } catch (\Exception $e) {
            $value = '/images/avatar.jpg';
        }
        return $value;
    }

    public function getImageFullUrlAttribute()
    {
        try {
            if ($this->image == NULL or !Storage::disk('s3')->exists($this->image)) {
                $image = '/images/avatar.jpg';
            } else {
                $image = Storage::disk('s3')->url($this->image);
            }
        } catch (\Exception $e) {
            $image = '/images/avatar.jpg';
        }
        return $image;
    }


    /******** Other methods ********/
    public function createVerificationToken(): void
    {
        $this->verification_token = createToken();
        $this->verification_token_created_at = Carbon::now();
        $this->save();
    }


}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Draft;
use App\Jobs\SelfDeleteUserAccount;
use App\Jobs\SendUserBannedEmail;
use App\Jobs\SendUserApplicationRejectedEmail;
use App\Jobs\SendUserApprovedEmail;
use App\Jobs\SendUserReactivatedEmail;
use App\Jobs\SendUserSuspendedEmail;
use App\Post;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('show', 'accountDeleted');
        $this->middleware('redirect_if_banned')->except('show');
        $this->middleware('needs_to_agree_to_policy_agreement')->except('show');
        $this->middleware('check_role:Admin', ['only' => [
            'manage',
            'approve',
            'reject',
            'suspend',
            'ban',
            'reactivate'
        ]]);
    }

    public function show(User $user)
    {
        if($user->is_banned_or_self_deactivated) {
            return abort(404);
        }
        $posts = Post::where('user_id', '=', $user->id)->orderBy('created_at', 'desc')->paginate(12);
        return view('users.show', compact('user', 'posts'));
    }

    public function selfDeactivate(): void
    {
        $user = Auth::user();
        $user->self_deactivated_at = now();
        $user->save();
        $user->posts()->delete();
        $user->drafts()->delete();
        $user->posts()->withTrashed()->update(['self_deactivated' => true]);
        foreach($user->posts() as $post) {
            Cache::tags(["post_$post->id"])->flush();
        }
        Cache::tags(['categories', 'posts'])->flush();
    }

    public function selfReactivate(): void
    {
        $user = Auth::user();
        $user->self_deactivated_at = NULL;
        $user->save();
        $user->posts()->withoutGlobalScopes()->restore();
        $user->drafts()->withoutGlobalScopes()->restore();
        $user->posts()->withoutGlobalScopes()->update(['self_deactivated' => false]);
        foreach($user->posts() as $post) {
            Cache::tags(["post_$post->id"])->flush();
        }
        Cache::tags(['categories', 'posts'])->flush();
    }

    public function deleteMyAccount()
    {
        return view('dashboard.self_delete');
    }

    public function selfDelete()
    {
        dispatch(new SelfDeleteUserAccount(Auth::user()));
        Auth::logout();
        session(['can_view_account_deleted_page' => true]);
        return redirect()->route('users.accountDeleted');
    }

    public function accountDeleted()
    {
        if (session('can_view_account_deleted_page') != true) {
            return abort(403);
        }
        return view('users.account_deleted');
    }

    public function manage(User $user)
    {
        return view('users.manage', compact('user'));
    }

    public function approve(User $user)
    {
        $user->role = 'Author';
        $user->status = 'Active';
        $user->save();
        dispatch(new SendUserApprovedEmail($user));
        return back()->with('approved', __('validation.user.approve.success-message', ['public_name' => $user->public_name]));
    }

    public function reject(Request $request, User $user)
    {
        $message = $request->message;
        $user->status = 'Rejected';
        $user->save();
        dispatch(new SendUserApplicationRejectedEmail($user, $message));
        return back();
    }

    public function suspend(User $user)
    {
        $user->status = 'Suspended';
        $user->suspended_count = $user->suspended_count+1;
        $user->suspended_at = now();
        $user->save();
        dispatch(new SendUserSuspendedEmail($user));
        return back();
    }

    public function unsuspend(User $user)
    {
        $user->status = 'Active';
        $user->suspended_at = NULL;
        $user->save();
        dispatch(new SendUserReactivatedEmail($user));
        return back()->with('reactivated', __('validation.user.reactivate.success-message', ['public_name' => $user->public_name]));
    }

    public function ban(User $user)
    {
        $user->status = 'Banned';
        $user->banned_count = $user->banned_count+1;
        $user->save();
        $user->posts()->delete();
        $user->drafts()->delete();
        dispatch(new SendUserBannedEmail($user));
        foreach($user->posts() as $post) {
            Cache::tags(["post_$post->id"])->flush();
        }
        Cache::tags(['categories', 'posts'])->flush();
        return back();
    }

    public function unban(User $user)
    {
        $user->status = 'Active';
        $user->save();
        dispatch(new SendUserReactivatedEmail($user));
        $user->posts()->restore();
        $user->drafts()->restore();
        foreach($user->posts() as $post) {
            Cache::tags(["post_$post->id"])->flush();
        }
        Cache::tags(['categories', 'posts'])->flush();
        return back()->with('reactivated', __('validation.user.reactivate.success-message', ['public_name' => $user->public_name]));

    }

}

resources/views/users/_author_block.blade.php
<div class="media author-block bordered margin-bottom ">
    <div class="media-left">
        <a href="{{ route('users.show', ['user' => $user->url]) }}">
            <img class="img-responsive" src="{{ $user->image_full_url }}" alt="">
        </a>
    </div>
    <div class="media-content">
        <h5><a href="{{ route('users.show', ['user' => $user->url]) }}">{{ $user->public_name }}</a></h5>
        @if($user->title)
            <p class="title margin-bottom">{{ $user->title }}</p>
        @endif
        @if($user->description)
            <p class="{{ $fullblock == false ? 'margin-bottom' : '' }}">
                @if($fullblock == false)
                    {{ $user->descriptionExcerpt }} @if(strlen($user->description) > 100)<a href="{{ route('users.show', ['user' => $user->url]) }}" class="view-more">view more</a>@endif
                @else
                    {{ $user->description }}
                @endif
            </p>
        @endif
        @if($fullblock == true)
            <div class="public_email">
                @if($user->public_email)
                    <p class="link"><a href="">{{ $user->public_email }}</a></p>
                @endif
                @if($user->public_email_2)
                    <p class="link"><a href="">{{ $user->public_email_2 }}</a></p>
                @endif
            </div>
            <div class="website">
                @if($user->website)
                    <p class="link"><a href="">{{ $user->website }}</a></p>
                @endif
                @if($user->website_2)
                    <p class="link"><a href="">{{ $user->website_2 }}</a></p>
                @endif
                @if($user->website_3)
                    <p class="link"><a href="">{{ $user->website_3 }}</a></p>
                @endif
            </div>
        @endif
        <p class="social-icons">
            @if($user->facebook)
                <a target=_blank href="{{ $user->facebook }}" title=Facebook>
                    <i class="fa fa-facebook"></i>
                </a>
            @endif
            @if($user->twitter)
                <a target=_blank href="{{ $user->twitter }}" title=Twitter>
                    <i class="fa fa-twitter"></i>
                </a>
            @endif
            @if($user->google_plus)
                <a target=_blank href="#" title=Google+>
                    <i class="fa fa-google-plus"></i>
                </a>
            @endif
            @if($user->youtube)
                <a target=_blank href="#" title=Youtube>
                    <i class="fa fa-youtube"></i>
                </a>
            @endif
            @if($user->vimeo)
                <a target=_blank href="#" title=Vimeo>
                    <i class="fa fa-vimeo"></i>
                </a>
            @endif
            @if($user->instagram)
                <a target=_blank href="#" title=Instagram>
                    <i class="fa fa-instagram"></i>
                </a>
            @endif
        </p>
    </div>
</div>

resources/views/users/account_deleted.blade.php
@extends('layouts.app')

@section('content')
    @component('templates.main_without_sidebar')
        {{--***** <div class="col-xs-12 main-content"> ***** --}}
            <div class="row text-center padding-top-for-mobile">
                <div class="col-xs-12 title-section padding-bottom">
                    <h2>Account Deleted</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
                    <p>We're sorry to see you going. Your account will be deleted and in the next few minutes.
                        All your drafts, posts and profile will be deleted from our system and we'll send a confirmation email once it's done !!
                    </p>
                    <p>We wish you all the best in all your endeavours. !!</p>
                </div>
            </div>
        {{--***** <div> ***** --}}
    @endcomponent
@endsection

resources/views/users/manage.blade.php
@extends('layouts.app')
@section('title', 'Contact')
@section('bodyId', 'contact')
@section('content')
    @component('templates.main_without_sidebar')
        <div id="user-management">
            <div class="floatk margin-bottom">
                <a class="button left" href="{{ route('dashboard.usersManagement') }}">Back to Dashboard</a>
            </div>
            @if($user->is_rejected)
                <div class="warning margin-bottom">
                    <p>This user was rejected</p>
                </div>
            @endif
            @if (session('approved'))
                <div class="success">
                    <p>{{ session('approved') }}</p>
                </div>
            @endif
            @if (session('reactivated'))
                <div class="success">
                    <p>{{ session('reactivated') }}</p>
                </div>
            @endif
            @if($user->is_suspended)
                <div class="warning margin-bottom">
                    <p>This user was suspended</p>
                </div>
            @endif
            @if($user->is_banned)
                <div class="warning margin-bottom">
                    <p>This user was banned</p>
                </div>
            @endif
            @if($user->is_applicant)
                <h4 class="page-title padding-bottom">New application</h4>
            @else
                <h4 class="page-title padding-bottom">Author's page</h4>
            @endif
            <h5>Applicant username: {{ $user->name }}</h5>
            <h5>Applicant public name: {{ $user->public_name }}</h5>
            <h5>Applicant's email: {{ $user->email }}</h5>
            @if($user->isApplicant)
                <h5>Application text: {{ $user->application_text }}</h5>
            @endif
            <h5>User status: {{ $user->status }}</h5>
            <h5>User role: {{ $user->role }}</h5>
            <h5>Sign up date: {{ $user->created_at }}</h5>
            <h5>Suspended count: {{ $user->suspended_count }}</h5>
            <h5>Post removed: {{ $user->posts_removed_count }}</h5>
            @if($user->isApplicant)
                <div class="margin-vt">
                    <a class="button" href="{{ route('users.approve', ['user' => $user->url]) }}">Approve</a>
                </div>
                <div class="hr"></div>
                <div class="margin-top">
                    <form action="{{ route('users.reject', ['user' => $user->url]) }}" method="POST">
                        {{ method_field('PUT') }}
                        {{ csrf_field() }}
                        <textarea name="message" id="" cols="30" rows="10"></textarea>
                        <button type="submit" class="button">Reject</button>
                    </form>
                </div>
            @elseif($user->is_author)
                <div class="margin-top">
                    @if(!$user->isBlocked)
                        <form action="{{ route('users.suspend', ['user' => $user->url]) }}">
                            @if(!$user->isSuspended)
                                <button type="submit" class="button margin-right">Suspend</button>
                            @else
                                <a class="button margin-top"
                                   href="{{ route('users.unsuspend', ['user' => $user->url]) }}">Unsuspend</a>
                            @endif
                        </form>
                    @endif
                    <div class="hr margin-vt">
                        @if(!$user->is_banned)
                            <a class="button margin-top" href="{{ route('users.ban', ['user' => $user]) }}">Ban</a>
                        @else
                            <a class="button margin-top" href="{{ route('users.unban', ['user' => $user]) }}">UnBan</a>
                        @endif
                    </div>
                </div>
            @endif
        </div>
    @endcomponent
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title', 'User')
@section('bodyId', 'user')
@section('content')
    @component('templates.main_with_sidebar')
        {{--***** <div class="col-xs-12 col-lg-8 main-content"> ***** --}}
        <div class="row">
            <div class="col-xs-12">
                <img class="padding-bottom img-responsive hidden-md hidden-lg" src="/images/adv-banner.jpg" alt="">
            </div>
        </div>
        <h4 class="page-title">{{ $user->public_name }}</h4>
        @include('users._author_block', ['user' => $user, 'fullblock' => true])
        <div class="category">
            <div class="header">
                <p class="header-title">Posts by this author</p>
            </div>
            <div class="row">
                @foreach($posts as $post)
                    <div class="col-xs-12 col-sm-6 col-md-4 padding-bottom-md">
                        <div data-aspect-ratio="custom" class="img-container">
                            <a href="{{ route('posts.show', ['category' => $post->category->url, 'post_slug' => $post->slug, 'post' => $post->id]) }}">
                                <img class="img-responsive" src="{{ $post->mediumImage }}" alt="">
                            </a>
                        </div>
                        <a href="{{ route('posts.show', ['category' => $post->category->url, 'post_slug' => $post->slug, 'post' => $post->id]) }}"><h4>{{ $post->title }}</h4></a>
                        <p class="info">
                            <span><a class="author" href="{{ route('users.show', ['user' => $user->url]) }}">{{ $user->public_name }}</a></span>
                            <span class="date">&middot; {{ $post->publication_date }}</span>
                        </p>
                    </div>
                @endforeach
                <div class="col-xs-12">
                    <div class="text-center">
                        {!! $posts->links() !!}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-md-6 hidden-lg">
                    <adsense
                            ad-client="ca-pub-3937376096447808"
                            ad-slot="3112785579"
                            ad-style="display: block"
                            ad-format="auto">
                    </adsense>
                </div>
                <div class="col-xs-12 col-md-6 hidden-lg">
                    <adsense
                            ad-client="ca-pub-3937376096447808"
                            ad-slot="3112785579"
                            ad-style="display: block"
                            ad-format="auto">
                    </adsense>
                </div>
            </div>
        </div>
        {{--***** </div> ***** --}}
    @endcomponent
@endsection