routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

// //route to test email. Enter the user id.
//Route::get('/mail', function() {
//    $user = \App\User::find(10);
//    return new \App\Mail\UserApprovedEmail($user);
//});

Auth::routes();

Route::get('/', 'PagesController@home');
Route::get('/policy-agreement', 'PagesController@policyAgreement')->name('policyAgreement');
Route::get('/agree-to-policy-agreement', 'PagesController@agreeToPolicyAgreement')->name('agreeToPolicyAgreement');
Route::get('/privacy', 'PagesController@privacy')->name('privacy');
Route::get('/terms', 'PagesController@terms')->name('terms');
Route::get('/guidelines', 'PagesController@guidelines')->name('guidelines');
Route::get('/search/{query?}/{page?}', 'SearchController@searchPage')->name('searchPage');
Route::get('/search_posts/{query}', 'SearchController@searchPosts');
Route::get('/menu_search/{query}', 'SearchController@menuSearch');

Route::get('/verification-email-sent', 'VerificationController@verificationEmailSent')->name('verify.verificationEmailSent');
Route::get('/verification-email-resent', 'VerificationController@verificationEmailResent')->name('verify.verificationEmailResent');
Route::get('/verify-email/{verification_token}', 'VerificationController@verifyEmail')->name('verify.verifyEmail');
Route::get('/email-verified', 'VerificationController@emailVerified')->name('verify.emailVerified');
Route::get('/email-not-verified/{auth_token}', 'VerificationController@emailNotVerified')->name('verify.emailNotVerified');
Route::get('/resend-verification-email/{auth_token}', 'VerificationController@resendVerificationEmail')->name('verify.resendVerificationEmail');
Route::get('/banned-user', 'VerificationController@bannedUser')->name('verify.bannedUser');

Route::get('/dashboard', 'DashboardController@summary')->name('dashboard');
Route::get('/dashboard/posts', 'DashboardController@posts')->name('dashboard.posts');
Route::get('/dashboard/views', 'DashboardController@views')->name('dashboard.views');
Route::get('/dashboard/profile', 'DashboardController@profile')->name('dashboard.profile');
Route::get('/dashboard/payments', 'DashboardController@payments')->name('dashboard.payments');
Route::get('/dashboard/users-management', 'DashboardController@usersManagement')->name('dashboard.usersManagement');
Route::get('/dashboard/posts-management', 'DashboardController@postsManagement')->name('dashboard.postsManagement');
Route::get('/dashboard/categories', 'DashboardController@categories')->name('dashboard.categories');
Route::post('/dashboard/categories', 'DashboardController@storeCategories')->name('dashboard.storeCategories');
Route::get('/dashboard/settings', 'DashboardController@settings')->name('dashboard.settings');

Route::put('/dashboard/update-profile', 'DashboardController@updateProfile');
Route::put('/dashboard/save-profile-image', 'DashboardController@saveProfileImage');
Route::put('/dashboard/update-personal-info', 'DashboardController@updatePersonalInfo');
Route::put('/dashboard/update-password', 'DashboardController@updatePassword');
Route::get('/dashboard/delete-my-account', 'UsersController@deleteMyAccount')->name('users.deleteMyAccount');
Route::get('/dashboard/search_posts', 'DashboardController@searchPosts');
Route::get('/dashboard/search_posts_for_all_users', 'DashboardController@searchPostsForAllUsers');
Route::get('/dashboard/search_users', 'DashboardController@searchUsers');
Route::get('/dashboard/search_views', 'DashboardController@searchViews');

Route::get('/users/{user}/manage', 'UsersController@manage')->name('users.manage');
Route::get('/users/{user}/approve', 'UsersController@approve')->name('users.approve');
Route::put('/users/{user}/reject', 'UsersController@reject')->name('users.reject');
Route::get('/users/{user}/suspend', 'UsersController@suspend')->name('users.suspend');
Route::get('/users/{user}/unsuspend', 'UsersController@unsuspend')->name('users.unsuspend');
Route::get('/users/{user}/ban', 'UsersController@ban')->name('users.ban');
Route::get('/users/{user}/unban', 'UsersController@unban')->name('users.unban');
Route::put('/users/self-deactivate', 'UsersController@selfDeactivate')->name('users.selfDeactivate');
Route::put('/users/self-reactivate', 'UsersController@selfReactivate')->name('users.selfReactivate');
Route::put('/users/self-delete', 'UsersController@selfDelete')->name('users.selfDelete');
Route::get('/users/account-deleted', 'UsersController@accountDeleted')->name('users.accountDeleted');
Route::get('/users/{user}', 'UsersController@show')->name('users.show');


Route::get('/posts/{draft}/edit', 'DraftsController@edit')->name('drafts.edit');
Route::put('/drafts/{draft}/update-category', 'DraftsController@updateCategory');
Route::put('/drafts/{draft}/update-media-type', 'DraftsController@updateMediaType');
Route::put('/drafts/{draft}/update-title', 'DraftsController@updateTitle');
Route::put('/drafts/{draft}/update-text', 'DraftsController@updateText');
Route::put('/drafts/{draft}/upload-image', 'DraftsController@uploadImage');
Route::put('/drafts/{draft}/reorder-images', 'DraftsController@reorderImages');
Route::delete('/drafts/{draft}/delete-image', 'DraftsController@deleteImage');
Route::put('/drafts/{draft}/update-video-id', 'DraftsController@updateVideoId');
Route::put('/drafts/{draft}/publish', 'DraftsController@publish');
Route::put('/drafts/{draft}/cancel-changes', 'DraftsController@cancelChanges');
Route::put('/drafts/{draft}/delete', 'DraftsController@delete');

Route::get('/posts/create', 'DraftsController@create')->name('drafts.create');
Route::put('/posts/toggle-remove', 'PostsController@toggleRemove')->name('posts.toggleRemove');

Route::get('/{category}/{post_slug}/{post_id}', 'PostsController@show')->name('posts.show');
// *** important *** this route should be last for performance reasons
Route::get('/{category}', 'PagesController@category')->name('category');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'auth_token', 'verification_token', 'verification_token_created_at', 'application_text',
        'image', 'public_name', 'url', 'title', 'description', 'public_email', 'public_email_2', 'website', 'website_2', 'website_3',
        'facebook', 'twitter', 'google_plus', 'youtube', 'vimeo', 'instagram', 'real_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'auth_token', 'verification_token', 'verification_token_created_at', 'application_text'
    ];

    public function getRouteKeyName()
    {
        return 'url';
    }

    /******** Relationships ********/
    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function drafts()
    {
        return $this->hasMany('App\Draft');
    }

    /******** Roles ********/
    // available roles: Unverified, Applicant, Author, Admin, Superadmin

    public function getIsSuperadminAttribute()
    {
        return $this->role === 'Superadmin';
    }

    public function getIsAdminAttribute()
    {
        return $this->role === 'Admin';
    }

    public function getIsAuthorAttribute()
    {
        return $this->role === 'Author';
    }

    public function getIsApplicantAttribute()
    {
        return $this->role === 'Applicant';
    }

    public function hasRoleOrHigher($role)
    {
        $response = false;
        if($role === 'Applicant') {
            if ($this->role == 'Applicant' || $this->role == 'Author' || $this->role == 'Admin' || $this->role == 'Superadmin') {
                $response = true;
            }
        } elseif($role === 'Author') {
            if($this->role == 'Author' || $this->role == 'Admin' || $this->role == 'Superadmin') {
                $response = true;
            }
        } elseif($role === 'Admin') {
            if($this->role == 'Admin' || $this->role == 'Superadmin') {
                $response = true;
            }
        } elseif($role === 'Superadmin') {
            if ($this->role == 'Superadmin') {
                $response = true;
            }
        }
        return $response;
    }

    /******** Status ********/
    // available status: Rejected, Active, Suspended, Banned

    public function getIsBannedAttribute()
    {
        return $this->status === 'Banned';
    }

    public function getIsBannedOrSelfDeactivatedAttribute()
    {
        return $this->status === 'Banned' || $this->self_deactivated_at != NULL;
    }

    public function getIsSelfDeactivatedAttribute()
    {
        return $this->self_deactivated_at != NULL;
    }

    public function getIsSuspendedAttribute()
    {
        return $this->status === 'Suspended';
    }

    /******** Scopes ********/


    /******** Accessors & Mutators ********/
    public function getDescriptionExcerptAttribute()
    {
        $descriptionExcerpt = str_limit(strip_tags($this->description), 100);
        return $descriptionExcerpt;
    }

    public function getImageAttribute($value)
    {
        try {
            if ($value == NULL or !Storage::disk('s3')->exists($value)) {
                $value = '/images/avatar.jpg';
            }
        } catch (\Exception $e) {
            $value = '/images/avatar.jpg';
        }
        return $value;
    }

    public function getImageFullUrlAttribute()
    {
        try {
            if ($this->image == NULL or !Storage::disk('s3')->exists($this->image)) {
                $image = '/images/avatar.jpg';
            } else {
                $image = Storage::disk('s3')->url($this->image);
            }
        } catch (\Exception $e) {
            $image = '/images/avatar.jpg';
        }
        return $image;
    }


    /******** Other methods ********/
    public function createVerificationToken(): void
    {
        $this->verification_token = createToken();
        $this->verification_token_created_at = Carbon::now();
        $this->save();
    }


}

resources/views/dashboard/categories.blade.php
@extends('layouts.app')
@section('bodyId', 'index')
@section('content')
    @component('dashboard.template')
        <div id="tab-profile" class="tab-content bordered">
            <div class="row">
                <div class="col-xs-12 col-lg-6 padding-bottom-md">
                    <div class="scroll">
                        <table>
                            <tbody>
                            <tr>
                                <th colspan="2" class="text-center bold">Current Categories</th>
                            </tr>
                            <tr>
                                <th class="bold">Name</th>
                                <th class="bold">Url</th>
                            </tr>
                            @foreach($allCategories as $category)
                                <tr>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->url }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-xs-12 col-lg-6 padding-bottom-md">
                    <form id="" role="form" method="POST" action="{{ route('dashboard.storeCategories') }}">
                        {{ csrf_field() }}
                        <label>
                            Category Name:
                            <input type="text" name="name">
                        </label>
                        <label>
                            Category Url:
                            <input type="text" name="url">
                        </label>
                        <div class="right">
                            <button class="button submit">Create new category</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endcomponent
@endsection

@section('javascripts')

@endsection

resources/views/dashboard/draft.blade.php
@extends('layouts.app')
@section('title', 'Post')
@section('bodyId', 'post')
@section('content')
    @component('templates.main_with_sidebar')
{{--<main>--}}
    {{--<div class="container">--}}
        {{--<div class="row">--}}
            {{--<div class="col-xs-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8 main-content">--}}
                <div class="post">
                    <div class="row padding-bottom">
                        <div class="col-xs-12">
                            <div class="float">
                                <a class="button left" href="{{ route('dashboard.posts') }}">Back to Dashboard</a>
                            </div>
                        </div>
                    </div>
                    <dashboard-draft :categories_prop="{{ $allCategories }}" :draft_prop="{{ $draft }}" :draft_images_prop="{{ $draftImages }}" :draft_youtube_video_prop="{{ $draftYoutubeVideo }}" :draft_vimeo_video_prop="{{ $draftVimeoVideo }}"></dashboard-draft>
                </div>
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</main>--}}
    @endcomponent
@endsection

resources/views/dashboard/drafts.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-drafts :user_prop="{{ Auth::user() }}"></dashboard-drafts>
    @endcomponent
@endsection

resources/views/dashboard/payments.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-payments></dashboard-payments>
    @endcomponent
@endsection

resources/views/dashboard/posts_management.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-posts-management></dashboard-posts-management>
    @endcomponent
@endsection

resources/views/dashboard/profile.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-profile :user_prop="{{ $user }}"></dashboard-profile>
    @endcomponent
@endsection

resources/views/dashboard/self_delete.blade.php
@extends('layouts.app')

@section('content')
    @component('templates.main_without_sidebar')
        {{--***** <div class="col-xs-12 main-content"> ***** --}}
        <div class="row padding-bottom">
            <div class="col-xs-12">
                <div class="float">
                    <a class="button left" href="{{ route('dashboard.posts') }}">Back to Dashboard</a>
                </div>
            </div>
        </div>
            <div class="row text-center padding-top-for-mobile">
                <div class="col-xs-12 title-section padding-bottom">
                    <h2>Delete my Account</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
                    <form method="POST" action="/users/self-delete">
                        {{ method_field('PUT') }}
                        {{ csrf_field() }}
                        <h4>Are you sure you want to permanently delete your account ?</h4>
                        <delete-my-account></delete-my-account>
                    </form>
                </div>
            </div>
        {{--***** <div> ***** --}}
    @endcomponent
@endsection

resources/views/dashboard/settings.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-settings :user_prop="{{ $user }}"></dashboard-settings>
    @endcomponent
@endsection

resources/views/dashboard/summary.blade.php
@extends('layouts.app')
@section('bodyId', 'index')
@section('content')
    @component('dashboard.template')
        <div id="tab-profile" class="tab-content bordered">
            <div class="row">
                <div class="col-xs-12">
                    @if($user->is_applicant)
                        <div>
                            <h4 class="padding-top">Hello {{ $user->public_name }}</h4>
                            <p>Your account is under review</p>
                        </div>
                    @endif
                    @if($user->is_suspended)
                        <div>
                            <h4 class="padding-top">Hello {{ $user->public_name }}</h4>
                            <p>You'be been suspended for 72hours. You won't be able to publish before {{ $suspendedUntil }}</p>
                        </div>
                    @endif
                </div>
                <div class="col-xs-12 col-lg-6 margin-bottom">
                    <div class="scroll">
                        <table>
                            <tbody>
                            <tr>
                                <th colspan="2" class="text-center bold">Posts</th>
                            </tr>
                            <tr>
                                <th class="bold">Posts published today</th>
                                <td>{{ $numberOfPostsToday }}</td>
                            </tr>
                            <tr>
                                <th class="bold">Views for posts published today</th>
                                <td>{{ $viewsForPostsPublishedToday }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-xs-12 col-lg-6 margin-bottom">
                    <div class="scroll">
                        <table>
                            <tbody>
                            <tr>
                                <th colspan="2" class="text-center bold">Account</th>
                            </tr>
                            <tr>
                                <th class="bold">Role</th>
                                <td><span>{{ $user->role }}</span></td>
                            </tr>
                            <tr>
                                <th class="bold">Status</th>
                                <td><span>{{ $user->status }}</span></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="margin-top">
                        <div class="scroll">
                            <table>
                                <tbody>
                                <tr>
                                    <th colspan="2" class="text-center bold">Payment</th>
                                </tr>
                                <tr>
                                    <th class="bold">Date of last payment</th>
                                    <td><span>NA</span></td>
                                </tr>
                                <tr>
                                    <th class="bold">Payment</th>
                                    <td><span>0$</span></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @if($user->is_superadmin)
                    <div class="col-xs-12">
                        <div class="margin-top">
                            <a class="button" target="_blank" href="/horizon">Visit horizon</a>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    @endcomponent
@endsection

@section('javascripts')

@endsection

resources/views/dashboard/template.blade.php
<main id="dashboard">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 main-content">
                <div class="dashboard">
                    <div class="tab-block">
                        <div class="scroll">
                            <div class="tab"><a class="{{ activeIf('dashboard') }}" href="{{ route('dashboard') }}">Summary</a></div>
                            @if(!Auth::user()->isSelfDeactivated)
                            <div class="tab"><a class="{{ activeIf('dashboard/posts') }}" href="{{ route('dashboard.posts') }}">Posts</a></div>
                            @endif
                            <div class="tab"><a class="{{ activeIf('dashboard/views') }}" href="{{ route('dashboard.views') }}">Views</a></div>
                            @if(!Auth::user()->isSelfDeactivated)
                            <div class="tab"><a class="{{ activeIf('dashboard/profile') }}" href="{{ route('dashboard.profile') }}">Profile</a></div>
                            @endif
                            <div class="tab"><a class="{{ activeIf('dashboard/payments') }}" href="{{ route('dashboard.payments') }}">Payments</a></div>
                            @if(Auth::user()->is_superadmin or Auth::user()->is_admin)
                            <div class="tab"><a class="{{ activeIf('dashboard/users-management') }}" href="{{ route('dashboard.usersManagement') }}">Users management</a></div>
                            @endif
                            @if(Auth::user()->is_superadmin or Auth::user()->is_admin)
                                <div class="tab"><a class="{{ activeIf('dashboard/posts-management') }}" href="{{ route('dashboard.postsManagement') }}">Posts management</a></div>
                            @endif
                            @if(Auth::user()->is_superadmin)
                                <div class="tab"><a class="{{ activeIf('dashboard/categories') }}" href="{{ route('dashboard.categories') }}">Categories</a></div>
                            @endif
                            <div class="tab"><a class="{{ activeIf('dashboard/settings') }}" href="{{ route('dashboard.settings') }}">Settings</a></div>
                        </div>
                        <div class="tab-contents">
                            {{ $slot }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

resources/views/dashboard/users_management.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-users-management></dashboard-users-management>
    @endcomponent
@endsection

resources/views/dashboard/views.blade.php
@extends('layouts.app')
@section('bodyId', 'posts')
@section('content')
    @component('dashboard.template')
        <dashboard-views :views_prop="{{ $views }}"></dashboard-views>
    @endcomponent
@endsection